# docker engine version 19.03.0+
version: '3.8'

services:

  # Our application to debug
  app:
    container_name: infiniloop-xdebug
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - '80:80'
    volumes:
        - './index.php:/var/www/html/index.php'
    environment:
      # https://xdebug.org/docs/all_settings
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 log=/tmp/xdebug.log discover_client_host=true